name: Flutter Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools platforms;android-34 build-tools;34.0.0

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/ndk
            /usr/local/lib/android/sdk/cmake
            ~/.android
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: android-sdk-${{ runner.os }}-ndk27-cmake3.22
          restore-keys: |
            android-sdk-${{ runner.os }}-
            android-sdk-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:arch:-stable"
          pub-cache-key: "flutter-pub-:os:-:channel:-:arch:-stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build/
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-
            flutter-deps-

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Android artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:arch:-stable"
          pub-cache-key: "flutter-pub-:os:-:channel:-:arch:-stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build/
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-
            flutter-deps-

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Linux desktop
        run: flutter build linux --release

      - name: Package Linux bundle
        working-directory: build/linux/x64/release
        run: tar -czf $GITHUB_WORKSPACE/linux-${{ github.event.release.tag_name }}.tar.gz bundle

      - name: Upload Linux artifact to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            linux-${{ github.event.release.tag_name }}.tar.gz

  macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:arch:-stable"
          pub-cache-key: "flutter-pub-:os:-:channel:-:arch:-stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build/
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-
            flutter-deps-

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build macOS desktop
        run: flutter build macos --release

      - name: Package .app as zip
        working-directory: build/macos/Build/Products/Release
        run: |
          APP_NAME=$(ls -d *.app | head -n 1)
          ditto -c -k --sequesterRsrc --keepParent "$APP_NAME" "$GITHUB_WORKSPACE/macos-${{ github.event.release.tag_name }}.zip"

      - name: Upload macOS artifact to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            macos-${{ github.event.release.tag_name }}.zip